### PR TITLE
fix: token factory data updates

### LINKED ISSUE #264: Cannot Burn tokens right after Minting them
Seems like there's a refetch missing, not sure.

Image

I minted 555 test tokens to my account but it says the balance is off.

Refreshing the page works fine.

### PR DESCRIPTION
**Pull request by chalabi2**
This pr fixes an issue where denoms did not immediatley show up in the DenomList after succesfull creation. 
This pr fixes an issue where balances in mint and burn forms didnt immediatley update after a succesfull tx.

Fixes #264

## Summary by CodeRabbit

- **New Features**
  - Token lists now update in real time as you type, ensuring that displayed results always reflect your current search.
  - After minting, burning, or confirming actions, account data such as balances, metadata, and total supply are automatically refreshed for the most up-to-date view.

- **Style**
  - Long URLs and logo texts are now truncated for a cleaner and more readable display.

### CODE REVIEW

File: components/factory/forms/BurnForm.tsx [hunk 1]
```diff
@@ -148,6 +149,10 @@ export default function BurnForm({
         onSuccess: () => {
           setAmount('');
           refetch();
```
Comment (fmorency) [inline components/factory/forms/BurnForm.tsx:151]: Can we remove `refetch` everywhere?

**Review by fmorency — APPROVED** [review]
ACK. Minor comment.

File: components/factory/forms/BurnForm.tsx (hunk 1 above)
Comment (chalabi2) [reply components/factory/forms/BurnForm.tsx:151]: we should consolidate this in a seperate pr so were not causing random refetch issues. I will tackle this in a seperate pr.
