### PR TITLE
fix: close vote detail modal when clicking backdrop

### LINKED ISSUE #325: Backdrop click does not close proposal info modal
**Describe the bug**
Clicking the backdrop is suppose to close the proposal info modal. 

**Additional context**
This worked prior to updating the proposal info modal.

### PR DESCRIPTION
**Pull request by fmorency**
This PR fixes closing the proposal details modal when clicking the backdrop.

Fixes #325 

## Summary by CodeRabbit

- **New Features**
  - The modal now supports closing by clicking on its main panel area, providing an intuitive exit mechanism.
  - Added a button for viewing tally results in the modal.
- **Style**
  - Enhanced styling dynamically reflects the modal's visibility state for a smoother user experience.
  - Improved layout organization within the modal for better user interaction.

### CODE REVIEW

File: components/groups/modals/voteDetailsModal.tsx [hunk 1]
```diff
@@ -203,7 +203,10 @@ function VoteDetailsModal({
     >
       <div className="fixed inset-0 bg-black/30" aria-hidden="true" />
 
-      <Dialog.Panel className="relative flex flex-col items-center justify-center w-full h-full">
+      <Dialog.Panel
+        className="relative flex flex-col items-center justify-center w-full h-full"
+        onClick={onClose}
```
Comment (hansl) [inline components/groups/modals/voteDetailsModal.tsx:208]: That closes the dialog when clicking the dialog's content, no?

Comment (fmorency) [reply components/groups/modals/voteDetailsModal.tsx:208]: No. Try it!

**Review by hansl — APPROVED** [review]
