### PR TITLE
fix: group info backdrop over sidenav

### LINKED ISSUE #326: Group Info modal z-index
**Describe the bug**
The group info modal's backdrop does not cover the sidenav.

### PR DESCRIPTION
**Pull request by fmorency**
This PR fixes group info backdrop over sidenav.

Fixes #326 

## Summary by CodeRabbit

- **Style**
	- Updated modal display behavior to show only when active.
	- Adjusted modal layout for improved centering within its parent container for a better user experience.

### CODE REVIEW

File: components/groups/modals/groupInfo.tsx [hunk 1]
```diff
@@ -169,7 +169,7 @@ export function GroupInfo({
     <Dialog
       open={showInfoModal}
       onClose={() => setShowInfoModal(false)}
-      className={`modal modal-open fixed flex p-0 m-0 z-0`}
+      className={`modal ${showInfoModal ? 'modal-open' : ''} fixed flex p-0 m-0`}
```
Comment (hansl) [inline components/groups/modals/groupInfo.tsx:172]: Fun fact; this will always be opened.

**Review by hansl — APPROVED** [review]
