### PR TITLE
fix: transaction issue from social wallets

### LINKED ISSUE #450: Transaction hanging
1) Log in with a social account, e.g., email
2) Perform a transaction, e.g., send tokens
3) Gracefully disconnect the wallet
4) Log in with a different social account, e.g., a different email
5) Perform a transaction, e.g., send tokens
6) The transaction will hang on the `...` animation.

No error is being displayed in the browser console.

The only way to get back into the wallet and make it work again is

- Reload the tab
- Click on Change Wallet
- Ignore the "Connection Error" that comes up and click the back arrow in the upper left of the window
- Click "Email" option for logging in
- Enter email for wallet that previously failed for Send Assets

Image

### PR DESCRIPTION
**Pull request by chalabi2**
fixes #450 

The issue was that the wallet was caching stale data in the ChainProvider for web3auth wallets

This PR does not meet the target coverage because it does not contain tests for the useTx hook but #466 does. 

## Summary by CodeRabbit

- **New Features**
  - Added a reset function to fully clear and reinitialize wallet and chain provider state, accessible from relevant modals and components.

- **Bug Fixes**
  - Improved transaction simulation error messages for greater clarity and support for more error types.
  - Enhanced handling of wallet address switching during transaction signing to reduce potential issues.

- **Chores**
  - Updated internal hooks and context to support comprehensive client and state resets.
  - Added tests for client reset functionality, web3 authentication context, and modal component behavior.

### CODE REVIEW

File: contexts/manifestAppProviders.tsx [hunk 1]
```diff
@@ -76,32 +77,49 @@ const ManifestChainProvider = ({ children }: { children: ReactNode }) => {
...
-          projectId: env.walletConnectKey,
-          relayUrl: 'wss://relay.walletconnect.org',
-          metadata: {
-            name: 'Alberto',
-            description: 'Manifest Network Web App',
-            url: 'https://alberto.com',
-            icons: [],
+    <Web3AuthContext.Provider value={contextValue}>
+      <ChainProvider
+        key={chainProviderKey} // This forces complete re-mount and reset of cosmos-kit
```
Comment (fmorency) [inline contexts/manifestAppProviders.tsx:97]: Cute. Internal React mechanism. The `key` parameter doesn't belong to `ChainProvider`.

**Review by fmorency — APPROVED** [review]
Thank you! Merging!
